export const iPhoneData = [
  {
    position: {
      page: 1,
      position: 3,
      global_position: 3,
    },
    asin: "B08L5RZTTK",
    price: {
      discounted: false,
      current_price: 829,
      currency: "USD",
      before_price: 0,
      savings_amount: 0,
      savings_percent: 0,
    },
    reviews: {
      total_reviews: 41,
      rating: 3.8,
    },
    url: "https://www.amazon.com/dp/B08L5RZTTK",
    score: "155.80",
    sponsored: false,
    amazonChoice: false,
    bestSeller: false,
    amazonPrime: true,
    title: "New Apple iPhone 12 (64GB, Green) [Locked] + Carrier Subscription",
    thumbnail: "https://m.media-amazon.com/images/I/71cQWYVtcBL._AC_UL320_.jpg",
  },
  {
    position: {
      page: 1,
      position: 4,
      global_position: 4,
    },
    asin: "B084GSMNRD",
    price: {
      discounted: false,
      current_price: 599,
      currency: "USD",
      before_price: 0,
      savings_amount: 0,
      savings_percent: 0,
    },
    reviews: {
      total_reviews: 101,
      rating: 4.6,
    },
    url: "https://www.amazon.com/dp/B084GSMNRD",
    score: "464.60",
    sponsored: false,
    amazonChoice: false,
    bestSeller: false,
    amazonPrime: true,
    title:
      "Sponsored Ad - Apple iPhone 11 [64GB, Purple] + Carrier Subscription [Cricket Wireless]",
    thumbnail: "https://m.media-amazon.com/images/I/71xn9bCRfhL._AC_UY218_.jpg",
  },
  {
    position: {
      page: 1,
      position: 5,
      global_position: 5,
    },
    asin: "B087623TMW",
    price: {
      discounted: false,
      current_price: 399,
      currency: "USD",
      before_price: 0,
      savings_amount: 0,
      savings_percent: 0,
    },
    reviews: {
      total_reviews: 161,
      rating: 4.4,
    },
    url: "https://www.amazon.com/dp/B087623TMW",
    score: "708.40",
    sponsored: false,
    amazonChoice: false,
    bestSeller: false,
    amazonPrime: true,
    title:
      "Sponsored Ad - New Apple iPhone SE (64GB, (Product) RED) [Locked] + Carrier Subscription",
    thumbnail: "https://m.media-amazon.com/images/I/810DvHOZ9nL._AC_UY218_.jpg",
  },
  {
    position: {
      page: 1,
      position: 6,
      global_position: 6,
    },
    asin: "B07P6Y7954",
    price: {
      discounted: true,
      current_price: 336,
      currency: "USD",
      before_price: 357,
      savings_amount: 21,
      savings_percent: 5.88,
    },
    reviews: {
      total_reviews: 21239,
      rating: 4.5,
    },
    url: "https://www.amazon.com/dp/B07P6Y7954",
    score: "95575.50",
    sponsored: false,
    amazonChoice: false,
    bestSeller: true,
    amazonPrime: true,
    title: "Apple iPhone XR, 64GB, Black - Fully Unlocked (Renewed)",
    thumbnail: "https://m.media-amazon.com/images/I/717KHGCJ6eL._AC_UY218_.jpg",
  },
  {
    position: {
      page: 1,
      position: 7,
      global_position: 7,
    },
    asin: "B077578W38",
    price: {
      discounted: false,
      current_price: 324.99,
      currency: "USD",
      before_price: 0,
      savings_amount: 0,
      savings_percent: 0,
    },
    reviews: {
      total_reviews: 7541,
      rating: 4.2,
    },
    url: "https://www.amazon.com/dp/B077578W38",
    score: "31672.20",
    sponsored: false,
    amazonChoice: false,
    bestSeller: false,
    amazonPrime: false,
    title: "Apple iPhone X, 64GB, Space Gray - Fully Unlocked (Renewed)",
    thumbnail: "https://m.media-amazon.com/images/I/61gVPTl5N3L._AC_UY218_.jpg",
  },
  {
    position: {
      page: 1,
      position: 8,
      global_position: 8,
    },
    asin: "B07ZQRMWVB",
    price: {
      discounted: false,
      current_price: 669.99,
      currency: "USD",
      before_price: 0,
      savings_amount: 0,
      savings_percent: 0,
    },
    reviews: {
      total_reviews: 447,
      rating: 4.4,
    },
    url: "https://www.amazon.com/dp/B07ZQRMWVB",
    score: "1966.80",
    sponsored: false,
    amazonChoice: false,
    bestSeller: false,
    amazonPrime: true,
    title:
      "Apple iPhone 11 Pro, 64GB, Midnight Green - Fully Unlocked (Renewed)",
    thumbnail: "https://m.media-amazon.com/images/I/61vflt1U5gL._AC_UY218_.jpg",
  },
  {
    position: {
      page: 1,
      position: 9,
      global_position: 9,
    },
    asin: "B07K8TVZ3J",
    price: {
      discounted: false,
      current_price: 539.95,
      currency: "USD",
      before_price: 0,
      savings_amount: 0,
      savings_percent: 0,
    },
    reviews: {
      total_reviews: 64,
      rating: 4.3,
    },
    url: "https://www.amazon.com/dp/B07K8TVZ3J",
    score: "275.20",
    sponsored: false,
    amazonChoice: false,
    bestSeller: false,
    amazonPrime: true,
    title: "Apple iPhone XS Max, 64GB, Gold - For Verizon (Renewed)",
    thumbnail: "https://m.media-amazon.com/images/I/51zJTtsQEnL._AC_UY218_.jpg",
  },
  {
    position: {
      page: 1,
      position: 10,
      global_position: 10,
    },
    asin: "B01N4R20RS",
    price: {
      discounted: true,
      current_price: 159.44,
      currency: "USD",
      before_price: 178.96,
      savings_amount: 19.52,
      savings_percent: 10.91,
    },
    reviews: {
      total_reviews: 27901,
      rating: 4.1,
    },
    url: "https://www.amazon.com/dp/B01N4R20RS",
    score: "114394.10",
    sponsored: false,
    amazonChoice: false,
    bestSeller: false,
    amazonPrime: true,
    title: "Apple iPhone 7, 32GB, Black - Fully Unlocked (Renewed)",
    thumbnail: "https://m.media-amazon.com/images/I/41ZtfBP1C6L._AC_UY218_.jpg",
  },
  {
    position: {
      page: 1,
      position: 11,
      global_position: 11,
    },
    asin: "B07Z4681LQ",
    price: {
      discounted: false,
      current_price: 882.86,
      currency: "USD",
      before_price: 0,
      savings_amount: 0,
      savings_percent: 0,
    },
    reviews: {
      total_reviews: 434,
      rating: 4.2,
    },
    url: "https://www.amazon.com/dp/B07Z4681LQ",
    score: "1822.80",
    sponsored: false,
    amazonChoice: false,
    bestSeller: false,
    amazonPrime: true,
    title:
      "Apple iPhone 11 Pro Max, 256GB, Midnight Green, Fully Unlocked (Renewed)",
    thumbnail: "https://m.media-amazon.com/images/I/61GggH1hAaL._AC_UY218_.jpg",
  },
  {
    position: {
      page: 1,
      position: 12,
      global_position: 12,
    },
    asin: "B07D6TT174",
    price: {
      discounted: true,
      current_price: 187.99,
      currency: "USD",
      before_price: 214,
      savings_amount: 26.01,
      savings_percent: 12.15,
    },
    reviews: {
      total_reviews: 19593,
      rating: 4.4,
    },
    url: "https://www.amazon.com/dp/B07D6TT174",
    score: "86209.20",
    sponsored: false,
    amazonChoice: false,
    bestSeller: false,
    amazonPrime: false,
    title: "Apple iPhone 8, 64GB, Space Gray - For AT&T (Renewed)",
    thumbnail: "https://m.media-amazon.com/images/I/81F-QC1N5WL._AC_UY218_.jpg",
  },
  {
    position: {
      page: 1,
      position: 13,
      global_position: 13,
    },
    asin: "B07SC58QBW",
    price: {
      discounted: true,
      current_price: 365,
      currency: "USD",
      before_price: 390,
      savings_amount: 25,
      savings_percent: 6.41,
    },
    reviews: {
      total_reviews: 5328,
      rating: 4.3,
    },
    url: "https://www.amazon.com/dp/B07SC58QBW",
    score: "22910.40",
    sponsored: false,
    amazonChoice: false,
    bestSeller: false,
    amazonPrime: false,
    title: "Apple iPhone XS, 64GB, Space Gray - Fully Unlocked (Renewed)",
    thumbnail: "https://m.media-amazon.com/images/I/71XeQzRDyML._AC_UY218_.jpg",
  },
  {
    position: {
      page: 1,
      position: 14,
      global_position: 14,
    },
    asin: "B07YYM3HFW",
    price: {
      discounted: true,
      current_price: 294,
      currency: "USD",
      before_price: 316.95,
      savings_amount: 22.95,
      savings_percent: 7.24,
    },
    reviews: {
      total_reviews: 11710,
      rating: 4.4,
    },
    url: "https://www.amazon.com/dp/B07YYM3HFW",
    score: "51524.00",
    sponsored: false,
    amazonChoice: false,
    bestSeller: false,
    amazonPrime: true,
    title: "Apple iPhone 8 Plus, 64GB, Space Gray - Fully Unlocked (Renewed)",
    thumbnail: "https://m.media-amazon.com/images/I/61K5-sw7yDL._AC_UY218_.jpg",
  },
  {
    position: {
      page: 1,
      position: 15,
      global_position: 15,
    },
    asin: "B07ZPJWGKZ",
    price: {
      discounted: false,
      current_price: 589,
      currency: "USD",
      before_price: 0,
      savings_amount: 0,
      savings_percent: 0,
    },
    reviews: {
      total_reviews: 431,
      rating: 4.5,
    },
    url: "https://www.amazon.com/dp/B07ZPJWGKZ",
    score: "1939.50",
    sponsored: false,
    amazonChoice: false,
    bestSeller: false,
    amazonPrime: true,
    title: "Apple iPhone 11, 128GB, Purple - Fully Unlocked (Renewed)",
    thumbnail: "https://m.media-amazon.com/images/I/615bu3CpN-L._AC_UY218_.jpg",
  },
  {
    position: {
      page: 1,
      position: 16,
      global_position: 16,
    },
    asin: "B07KFN43WC",
    price: {
      discounted: false,
      current_price: 0,
      currency: "USD",
      before_price: 0,
      savings_amount: 0,
      savings_percent: 0,
    },
    reviews: {
      total_reviews: 5700,
      rating: 4.5,
    },
    url: "https://www.amazon.com/dp/B07KFN43WC",
    score: "25650.00",
    sponsored: false,
    amazonChoice: false,
    bestSeller: false,
    amazonPrime: false,
    title: "Apple iPhone XS Max, 256GB, Gold - Fully Unlocked (Renewed)",
    thumbnail: "https://m.media-amazon.com/images/I/71isxv6Wd-L._AC_UY218_.jpg",
  },
  {
    position: {
      page: 1,
      position: 17,
      global_position: 17,
    },
    asin: "B07B9P995P",
    price: {
      discounted: false,
      current_price: 226.3,
      currency: "USD",
      before_price: 0,
      savings_amount: 0,
      savings_percent: 0,
    },
    reviews: {
      total_reviews: 690,
      rating: 4.4,
    },
    url: "https://www.amazon.com/dp/B07B9P995P",
    score: "3036.00",
    sponsored: false,
    amazonChoice: false,
    bestSeller: false,
    amazonPrime: true,
    title: "Apple iPhone 8, 64GB, Silver - Fully Unlocked (Renewed)",
    thumbnail: "https://m.media-amazon.com/images/I/718cuNZTR8L._AC_UY218_.jpg",
  },
  {
    position: {
      page: 1,
      position: 18,
      global_position: 18,
    },
    asin: "B07HKQ61NV",
    price: {
      discounted: true,
      current_price: 199.99,
      currency: "USD",
      before_price: 219,
      savings_amount: 19.01,
      savings_percent: 8.68,
    },
    reviews: {
      total_reviews: 1167,
      rating: 4.4,
    },
    url: "https://www.amazon.com/dp/B07HKQ61NV",
    score: "5134.80",
    sponsored: false,
    amazonChoice: false,
    bestSeller: false,
    amazonPrime: true,
    title: "Apple iPhone 8 a1905 64GB LTE GSM Unlocked (Renewed)",
    thumbnail: "https://m.media-amazon.com/images/I/71aOr1CuM1L._AC_UY218_.jpg",
  },
  {
    position: {
      page: 1,
      position: 19,
      global_position: 19,
    },
    asin: "B079C558S8",
    price: {
      discounted: true,
      current_price: 192,
      currency: "USD",
      before_price: 220,
      savings_amount: 28,
      savings_percent: 12.73,
    },
    reviews: {
      total_reviews: 158,
      rating: 4.4,
    },
    url: "https://www.amazon.com/dp/B079C558S8",
    score: "695.20",
    sponsored: false,
    amazonChoice: false,
    bestSeller: false,
    amazonPrime: false,
    title: "Apple iPhone 8 64GB, Verizon, Space Gray (Renewed)",
    thumbnail: "https://m.media-amazon.com/images/I/71loPUcAeML._AC_UY218_.jpg",
  },
  {
    position: {
      page: 1,
      position: 20,
      global_position: 20,
    },
    asin: "B079RWXLBL",
    price: {
      discounted: true,
      current_price: 275,
      currency: "USD",
      before_price: 289.99,
      savings_amount: 14.99,
      savings_percent: 5.17,
    },
    reviews: {
      total_reviews: 518,
      rating: 4.3,
    },
    url: "https://www.amazon.com/dp/B079RWXLBL",
    score: "2227.40",
    sponsored: false,
    amazonChoice: false,
    bestSeller: false,
    amazonPrime: false,
    title: "Apple iPhone 8 256GB GSM Unlocked Phone, Gold (Renewed)",
    thumbnail: "https://m.media-amazon.com/images/I/51hD+WlSEgL._AC_UY218_.jpg",
  },
  {
    position: {
      page: 1,
      position: 21,
      global_position: 21,
    },
    asin: "B07K2K9WDL",
    price: {
      discounted: true,
      current_price: 179,
      currency: "USD",
      before_price: 196,
      savings_amount: 17,
      savings_percent: 8.67,
    },
    reviews: {
      total_reviews: 568,
      rating: 4.3,
    },
    url: "https://www.amazon.com/dp/B07K2K9WDL",
    score: "2442.40",
    sponsored: false,
    amazonChoice: false,
    bestSeller: false,
    amazonPrime: false,
    title: "Apple iPhone 7 a1778, GSM Unlocked, 32GB (Renewed)",
    thumbnail: "https://m.media-amazon.com/images/I/71x3e0x+M2L._AC_UY218_.jpg",
  },
  {
    position: {
      page: 1,
      position: 22,
      global_position: 22,
    },
    asin: "B08CL51X7Y",
    price: {
      discounted: true,
      current_price: 55,
      currency: "USD",
      before_price: 59.99,
      savings_amount: 4.99,
      savings_percent: 8.32,
    },
    reviews: {
      total_reviews: 202,
      rating: 4.4,
    },
    url: "https://www.amazon.com/dp/B08CL51X7Y",
    score: "888.80",
    sponsored: false,
    amazonChoice: false,
    bestSeller: false,
    amazonPrime: true,
    title:
      "Sponsored Ad - Net10 Samsung Galaxy A01 4G LTE Prepaid Smartphone - Black - 16GB - Sim Card Included -CDMA",
    thumbnail: "https://m.media-amazon.com/images/I/71IcHiqLf1L._AC_UY218_.jpg",
  },
  {
    position: {
      page: 1,
      position: 23,
      global_position: 23,
    },
    asin: "B07Y5V6LMT",
    price: {
      discounted: false,
      current_price: 39.99,
      currency: "USD",
      before_price: 0,
      savings_amount: 0,
      savings_percent: 0,
    },
    reviews: {
      total_reviews: 62,
      rating: 4.4,
    },
    url: "https://www.amazon.com/dp/B07Y5V6LMT",
    score: "272.80",
    sponsored: false,
    amazonChoice: false,
    bestSeller: false,
    amazonPrime: true,
    title:
      "Sponsored Ad - Net10 LG Journey 4G LTE Prepaid Smartphone (Locked) - Black - 16GB - Sim Card Included - CDMA",
    thumbnail: "https://m.media-amazon.com/images/I/61cRXYdjAyL._AC_UY218_.jpg",
  },
  {
    position: {
      page: 1,
      position: 24,
      global_position: 24,
    },
    asin: "B07Y5V386B",
    price: {
      discounted: false,
      current_price: 59.99,
      currency: "USD",
      before_price: 0,
      savings_amount: 0,
      savings_percent: 0,
    },
    reviews: {
      total_reviews: 19,
      rating: 4.3,
    },
    url: "https://www.amazon.com/dp/B07Y5V386B",
    score: "81.70",
    sponsored: false,
    amazonChoice: false,
    bestSeller: false,
    amazonPrime: true,
    title:
      "Sponsored Ad - Net10 Samsung Galaxy J2 4G LTE Prepaid Smartphone (Locked) - Black - 16GB - Sim Card Included - CDMA",
    thumbnail: "https://m.media-amazon.com/images/I/7141GkAckUL._AC_UY218_.jpg",
  },
  {
    position: {
      page: 1,
      position: 25,
      global_position: 25,
    },
    asin: "B08CL5326M",
    price: {
      discounted: false,
      current_price: 39.99,
      currency: "USD",
      before_price: 0,
      savings_amount: 0,
      savings_percent: 0,
    },
    reviews: {
      total_reviews: 89,
      rating: 4.4,
    },
    url: "https://www.amazon.com/dp/B08CL5326M",
    score: "391.60",
    sponsored: false,
    amazonChoice: false,
    bestSeller: false,
    amazonPrime: true,
    title:
      "Sponsored Ad - Net10 Motorola Moto E6 4G LTE Prepaid Smartphone (Locked) - Black - 16GB - Sim Card Included - CDMA",
    thumbnail: "https://m.media-amazon.com/images/I/717XlkayF+L._AC_UY218_.jpg",
  },
];
